### ISSUE TITLE
Provider release schedule

### ISSUE THREAD

**Issue by FrenchBen** [terraform-providers/terraform-provider-tls#12]
Out of curiosity, how often is this provider module updated? With my recent PR being merged, I'd love to be able to start using it. 
Trying to get an idea of the schedule behind this. 

Thanks
/cc @vancluever @apparentlymart

**Comment by vancluever** [comment]
Hey everyone - I'll make this an item to do next week.

BTW: Releases for providers are done separate of TF core now, since the provider split back in the summer of last year.

**Comment by vancluever** [comment]
Hey everyone, this was actually released last week! Thanks @apparentlymart!
